# !! Attention !!
version: '3.5'

services:
  leaf_dc_bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - DISCORD_API_KEY=${LEAF_API_KEY}
